### ISSUE TITLE
RM Priority #5.3 - Product Security Dashboard

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1012]
RM - stands for Road Map

As part of the RM High Level Priority #5: Improve Platform Product Registry service.

Introduce Product Security Dashboard to display valuable security insights for each application.

As security tooling becomes more highly integrated into OCP projects, there is a desire to centralize this information to make it more accessible to interested parties.

From the Platform Registry, each application should have a Security Section that includes the following:

- [ ] Link(s) to associated github repo(s) with last update status
- [ ] Check manifests for static code analysis (i.e. codeQL, SonarX)
- [ ] Check manifests for dynamic code analysis (i.e. OWASP Zap)
- [ ] Check to see if scanned by ACS and link for scan results
- [ ] Letter score for app security based on having tools in place and results for each project

There are tickets in the developer experience board that are assigned to the ops and shared services workstream:

In Backlog:

- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/1780
- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/1781
- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/1715
- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/1713
- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/1712
- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/1711

Closed:

- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/2532
- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/1714

Here we'll be tracking tickets related to the Security Dashboard that will be for the app dev team to work on.

**Comment by NickCorcoran** [comment]
Instead of checking repos for static/dynamic analysis we decided to PoC the use of our own SonarQube and OWASP ZAP scanners to scan all repos/app routes and keep results in a local database within the registry.  This is an adjustment from #1712 and #1713.

**Comment by Iryna-Kaplun** [comment]
Nick's comment from July 18, 2024:

> Dev Experience team were working on something that got delayed due to our need to do IDIR integration for GItHub.  I'm hoping we can get back to that very soon.  I'm hoping it will make this Epic obsolete.  How about we close it for now and we can always revisit/reopen if DevX can't do what I'm hoping.

>
