### ISSUE TITLE
Next.js Learning for new Registry

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1021]
Describe the issue
The new registry will be built using Next.js, so this is a checklist to learn Next.js before proceeding to implementing features on the new registry.

Prerequisite

- [ ]  Understand React.js
- [ ]  Understand differences between npm, npx, nvm and when to use them

Additional Context

- [ ]  Understand the project structure and file organization
- [ ]  Learn the file-based routing system and navigating using the Link component
- [ ]  Create reusable components
- [ ]  Fetch data from external APIs
- [ ]  Style application with tailwind
- [ ]  Understand useState and useEffect hooks
- [ ]  Learn how user authentication and sessions work for logins

Dependencies

Ask Oamar for info regarding new registry. Billy regarding plans for Christopher
Definition of done/Acceptance Criteria

Implement a simple feature for new registry, refer to issue #4137
