### ISSUE TITLE
Before Go-Live Bugs in the New Registry

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#1481]
Priority: high (H), medium (M), low (L)
Effort/size: large (L), medium (M), small (S)
Urgency: Wait (until after go-life), Urgent (before go-life)

**Urgent bugs to fix before the go-life with the new UI:** 

- [x] 1. ~The list of ministries doesn't have all the ministries. UPD: Now Private Cloud lacks the HOUS ministry only, and Public Cloud lacks 25 ministries. - Urgent. Priority: H. Size: L. Assignee: Zhanna (combine with #2 in one ticket). Ticket #1508~ **- FIXED**
- [x] 2. ~The list of clusters doesn't have all the clusters. It lacks - Urgent. Priority: H. Size: S. Assignee: Zhanna.~ **- FIXED**
- [x] 4. ~Empty List “Request a New Project Set” button in Public Cloud leads to creation of Private Cloud Product. - Urgent. Priority: H. Size: S. Assignee: Oamar. Ticket #1510~ **- FIXED**
- [x] 5. ~Public Cloud Filters have Clusters in them. - Urgent. Priority: H. Size: S. Assignee: Zhanna. Ticket #1511~ **- FIXED**
- [x] 6. ~Both Modal windows after Submit in Private Cloud show the information about the Public Cloud. - Urgent. Priority: H, Size: S. Assignee: Christopher. Ticket #1512~ **- FIXED**
- [x] ~7. The filter on Requests and Product tabs lacks two clusters. - Urgent. Priority: H, Size: S. Assignee: Zhanna (combine with #8 in one ticket).~ **- FIXED**
- [x] 8. <s> As a User I see KLAB cluster. - Urgent. Priority: H, Size: S.Assignee: Zhanna. Ticket #1514 - Still see LAB clusters as a User.</s>
- [x] ~9. We have a footer but none of the links go anywhere. We need to put info into the footer. Find what should go into the footer and add it there - Urgent. Priority: H. Size: S/M. Assignee: Amritpal. Ticket #1515~ **- FIXED**
- [x] 10. ~Search by license plate does not work in Products Tab/View All. - Urgent. Priority: M, Size: M/L. Assignee: Oamar. Ticket #1516~**- FIXED**
Adding blocking issues from below:
- [x] <s> 30. If the product has a Secondary TL the license plate is overlapping their name. - Artem to test if it's been fixed. </s> **- FIXED**
- [x] <s> 31. If the product has a Secondary TL, their snippet is not unfolded by default. You can see that they are present and their name only if you click a button "Add Secondary TL". Amritpal/3 </s> **- FIXED**
- [x] <s> 33. Account Coding is empty when a user edits the product. </s> **- FIXED**
- [x] <s>  49. As an Admin I can’t approve products </s> **- FIXED**
- [x]  ~50. Create request doesn’t send emails. UPD: now all the emails are broken - Artem and Oamar will connect to debug this one. - Ticket #1740~ **- FIXED**
- [x] <s>  60. After user logs in, they are redirected to the create page https://dev-pltsvc.apps.silver.devops.gov.bc.ca/private-cloud/create but needs to be redirected to https://dev-pltsvc.apps.silver.devops.gov.bc.ca/. Ticket #1700</s> **- FIXED**
- [x]  <s>45. Allowing decimal in Budget for Public Cloud was a requirement from Olena and Public Cloud team when we implemented it.  Ticket #1699 </s> **- FIXED**
- [x]  <s>58. Remove GitHub as a login option - Ticket #1736 </s> **- FIXED**
- [x] <s>64. AWS Roles mentions Projects instead of Products - Zhanna. Ticket #1744</s> **- FIXED**
- [x]  ~65. The back button works as a back button for the browser - Zhanna. Ticket #1745~ **- FIXED**
- [x]  <s>66. When components are rerendered the user is moved to the Products tab - Oamar. Ticket #1746</s> **- FIXED**
- [x]  ~62. If the user edits the existing Product and doesn't touch the Common Components section, clicking Submit triggers an error, because they are empty by default. Though the user has filled or clicked ignore while making the Create Request - Oamar. Ticket #1747~ - **Cancelled**
- [x]  ~67. Final touch on Email templates - Ticket #1680. Ticket #1811~ **- FIXED**
- [x]  ~72. Deletion does not work (products are always fail the Deletion check) - Artem is looking into env variables. UPD: After adding variables the Delete button is disabled even if license plate and PO email are typed in:
Ticket #1853~
- [x] ~82. Hitting Enter after input of search prompt erases it. Ticket #1975~ **- FIXED**
- [x] ~87. Spell ministries instead of Acronyms (e.g. Citizen Services instead CITZ). Ticket #1976~ **- FIXED**
- [x] <s> Ticket #2003 for the following visual bugs: 

> - 88). Create and Product Page in Private Cloud: a. change "Cluster" to "Private Cloud OpenShift platform hosting tier". b. Under the cluster dropdown: "Please read more about tiers here" where "here" is a link to https://digital.gov.bc.ca/cloud/services/private/products-tools/hosting-tiers/
> - 89). Login Page: change "product resource quota increases and downgrades (including CPU/RAM/Storage.)" to "product resource changes."
> -  90). Create Page. Add "Provisioning request from new teams that haven't had an onboarding meeting won't be approved."
> - 92). Change the description on the In Progress tab to: "These products have pending requests and admins are approving them."
> - 105). Both on Private and Public Cloud Product Tab: a. change "There are no requests" to "There are no products", b. delete "You currently have no provisioning requests for the Private Cloud Openshift Platform" completely, c. change in link text: "PROJECT SET" to "PRODUCT".
> - 111). On Products and Requests Tab change Deployed in Public Cloud to Created (as it is now in Private Cloud).
> - 113). In Deletion Popup change "Project" to "Product" and change "product set" to just "product".
> - 114). If the Product is not ready to be deleted add a sentence: "Please remove all pods and PVCs from all four namespaces before trying to delete again."
> - 115). Second modal on Approval: change product set or project set to just product (-s).
> - 116). On Public Cloud Create, Request and Product pages under Provider dropdown add text "Read more about Public Cloud Service Providers here", where "here" is a link to https://digital.gov.bc.ca/cloud/services/public/providers/
> - 117). Delete "- Project Set Provisioning Request" in the header of Product Page.</s> 

- [x] ~91. Return old look of the Contacts on the Products and In Progress tabs. Ticket #1977~ **- FIXED**
- [x] ~93. Amritpal and Pillar will review emails templates and their headers on logical and wording errors. Ticket #1978 for the below bullet point 94-104:~ **- FIXED**

> - 94).  Email Templates. Change phrase "The new Product or Technical Lead provided" to "The new Product Owner or Technical Lead". Also add "(-s)" after "Lead" in the phrase "The Product Owner and the Technical Lead have been".
> - 95). Email Templates. In all the email regarding Editing and Deleting remove all mentions of "new project set".
> - 96). Email Templates. Change the header of Request Received email headers to this: "Provisioning request received for the product name in AWS (for Public Cloud) / OpenShift (for Private Cloud).
> - 98). Email Templates. Change "Hi <name of the project>'s Team" to "Hi Product Team". 
> - 99). Email Templates. Change any mentions of Rocket Chat channels to just one: #devops-operations.
> - 100). Email Templates. Deletion request received email, change wording. "Your product deletion request for <Product name> has been received." Same for Deletion Approved but "has been received and completed". 
> - 101). Email Templates. Add default quotas to Provisioned email.
> - 102). Email Templates. Admin comment is not shown in Rejected email.
> - 103). Email Templates. Edit Request: "Your request for a resource quota has been completed. You can login to OpenShift cluster console using the link above and you will see the new resource quota values."
> - 104). Email Templates. Provisioning request received: "Provisioning request received for the product name in AWS/ OpenShift."
- [x] ~97. Email Templates. Change the signage in the bottom to Platform Services Team for Private Cloud and to Cloud Pathfinder Team for Public Cloud templates. Ticket #2036~ **- FIXED**
- [x] ~106. Search on Prod shows "1 of 2 results" on UI though two products in the downloaded .csv. Ticket #1979~ **- FIXED**
- [x] ~107. Search doesn't work if there is an apostrophe in the name of the Product. Ticket #1980~ **- FIXED**
- [x] ~112. Search doesn't work in Public Cloud on Prod. "Test" and "Website" don't display expected result. Ticket #1981~ **- FIXED**
- [x] ~79. The users added to the Public Cloud Product in New UI shows it has no UPN in the Current Registry. Those users have UPN in AD. Ticket #2056~ **- FIXED**
- [x] ~119. The confirmation Deletion modal window is the same as for New Project Set. Needs to be changed to Deletion relevant content~ **- FIXED**
- [x] ~120. The Products that were deleted and went through Provisioning of the Deletion are still shown in both Old and New Registry. Example on Prod: b88b53 Ticket #2096~ **- FIXED**
- [x] ~124. Add a disclaimer with unblocking checkbox if one of AG ministries umbrella is chosen. Ticket #2127~ **- FIXED**

======================================================================================
**Wait until after the go-life to fix these:** 
- [ ] 3.  Logo is leading to the Private Cloud products page even on the Public Cloud tab. - It would be nice to do before go-live. Priority: M. Size: S. Assignee: Oamar. Ticket #1509
- [ ] 11. When the Product is Provisioned it's status is not updated on the page automatically. User has to refresh the page - Wait. New feature, not a bug.  Size: L. Priority: H
- [ ] 12. Add human friendly names for the ministries - Wait but it would nice to do before. Priority: M. Size: M
- [ ] 13. The bearer token in the test is “abcd”. Should we change it to be received from the authentication website? Actually it works without token too - Wait. Priority: L/M. Size: S/M
- [ ] 14. Now after login we are redirected to Private Cloud products. What will be the case when a user only uses Registry for Public Cloud only? - Wait. Priority: L. Size: TBD
- [ ] 15. If one of AG, EMBC, HOUS or PSSG ministries is chosen, the disclaimer with checkbox is not showing up. - Wait. Priority: H. Size: M. *Note: "Disclaimer" is misspelled in the footer.
- [ ] 16. Input in Search fields makes the live search but if user hits Enter in the end the Search condition is erased. - Wait. Priority: L, Size: S
- [x] 17.<s> Pagination does not work together with Search (not able to visit other than first page). - fixed. Artem to check if this is working now </s> - **FIXED**
- [x] 18. <s>In the New Registry there's no filtering by Ministry. It may be handy for persons like Ryan Loiselle who helps all four ministries under AG umbrella. Though there is a workaround of searching by Ministry but you can't search by name in this case. - fixed. Artem to check if this is working now </s> - **FIXED**
- [ ] 19. The Requests are not sorted by name, nor creation date, nor last edit date, nor request type - _will be fixed in Oamar's PR. Artem to check and test once completed._ NOT FIXED
- [x] 20. <s>After changing the Description the Request is stuck in Processing on Test </s>- **FIXED** in #1282
- [x] 21. ~No indicator if a product has an active request - _will be fixed in Oamar's PR. Artem to check and test once completed._~ - **FIXED**
- [x] 22. ~If Admin rejects the Request he sees a Modal Window for the Request Creation submitted successfully - assigned to Amritpal/ 3~ - **FIXED**
- [ ] 23. Now we have the namespaces shown but they are not links that lead to OpenShift - _will be fixed in Oamar's PR. Artem to check and test once completed._
- [x] 24. ~If user Edits anything but not touches the quota the Modal Window wording says to describe why they changed the quota. Below it says that user needs the onboarding session though it's an Edit request. The second Modal Window says that the new project set has been received.  assigned to Amritpal~ - **FIXED**
- [x] 25. ~When the Product is approved, the description on Product Page has wording about onboarding process which in this case is already passed (issue moved from option 10 #1353)~ **- FIXED**
- [x] 26. ~The name field on Public Cloud creation page has no description of allowed/non-allowed symbols (issue moved from option 5 #1353)~ - **FIXED**
- [x] 27. ~If Admin clicks Approve in Public Cloud, they see the modal window with wording for successful project creation for Private Cloud. Amritpal/2~
- [x] 28. ~Login page has two typos: "IDR" instead of "IDIR"~ **- FIXED**
- [x] 29. ~The Login Page has a disclaimer about Public Cloud in the very bottom. Not sure if it needs to be there or it was copied in there by default. If not, we could change the wording to mention that it's needed for Public Cloud only.~  **- FIXED**
- [x] 30. <s>If the product has a Secondary TL the license plate is overlapping their name. Artem double check it, please</s> **- FIXED**
- [x] 31. <s>If the product has a Secondary TL, their snippet is not unfolded by default. You can see that they are present and their name only if you click a button "Add Secondary TL". Amritpal/3</s> **- FIXED**
- [x] 32. If you unfold Secondary TL and try to fold the snippet back you will remove them, because the button immediately becomes a Remove button. Maybe we could implement an alert of some kind or a popup to let users know. - Amritpal/2
- [x] 33. <s>Account Coding is empty when a user edits the product.  Artem double check it, please</s> **- FIXED**

Feedback from Max:
- [x]  34.  <s> When I navigate to a different page and back my changes are erased. Don’t think this is a big deal, but it becomes an issue when links don’t open in new tabs (like the cost calculator link mentioned below).</s> **- FIXED**
- [x] 35. <s> There is a “tool tip” question mark by the monthly spend input boxes that I would expect to have some sort of pop up when I hover over it or click it, but it doesn’t </s> **- FIXED**
- [x] 36. <s> There is a note that says “There will be a base charge of CAD 400 to 600 per month for each project set created” however the default billing estimation is 200 (unitless). I think a change here would be adding a USD unit to the billing estimation boxes, or changing the note to be in USD as well. It’s slightly confusing as it is </s> **- FIXED**
- [x]  37. <s>The arrows on the input boxes don’t make a lot of sense as they increment by cents, and these are estimates.</s> **- FIXED**
- [x]  38. <s> The link to the cost calculator is wrong, should be https://calculator.aws/#/. This should also open in a new tab so that the form entries aren’t erased</s> - **FIXED**
- [ ]  39. I think that when an entry is not accepted the specific box that is wrong would be highlighted. I found entering incorrect account codes it would not tell me specifically what was wrong, only that it was wrong
- [x]  40. <s> All the modal stuff looks and feels good but at the end I click “back to dashboard” or something and I get a 404 on this page https://dev-pltsvc.apps.silver.devops.gov.bc.ca/public-cloud/requests</s> - **FIXED**
- [x]  41. <s> Just one tidbit here, is that when I have two technical leads the second box is not expanded when I am editing, I have to click “add secondary technical lead” to see the second technical lead. Everything else looks good, other than some of the same stuff mentioned above.</s> - **FIXED**
- [x]  42. <s> I get a 404 on the export button for the public cloud, which doesn’t seem to be an issue on the private cloud side. It’s on a GET request to this endpoint: https://dev-pltsvc.apps.silver.devops.gov.bc.ca/api/public-cloud/allprojects?</s> - **FIXED**

Feedback from Prabhu:
- [x]  43.<s>  For the base costs in the new project section we need to specify that the costs taken are in USD </s> - **FIXED**
- [ ]  44. Restricting special characters for some feilds is a necessary requirement
- [x]  <s>45. Same for the account coding as it should just be numbers and letters but the UI is accepting special characters </s> - **FIXED**
- [ ]  46. The inprogress tab is a bit confusing, Admins would see all the requests but PO’s would see the requests associated with just their project set ?
- [x]  47. <s>Export functionality is doesn’t seem to be working </s> - **FIXED**

Feedback after session with Iryna:
- [x]  48. ~Remove LAB mentioning~ **- FIXED**
- [x]  49. <s>As an Admin I can’t approve products</s> **- FIXED**
- [ ]  50. Create request doesn’t send emails
- [ ]  51. Return Decimal to Account Coding
- [ ]  52. Account Coding is editable in Pending Request view
- [ ]  53. Change or remove name in the Email as TL gets the name of PO there
- [ ]  54. Exceeding comments and dividers in emails
- [ ]  55. The emails do not show the comments from admin

**Newly found bugs:**
- [x]  ~56. When pressing the submit edit request in public cloud for a product that already exists the user sees a window for a submission request~
- [ ]  57. The old users have the names that were taken from IDIR a long time ago
- [x]  <s>58. Remove GitHub as a login option - Ticket #1736 </s> **- FIXED**
- [x]  ~59. The bc gov logo favicon is squished~
- [x]  60. <s>After user logs in, they are redirected to the create page https://dev-pltsvc.apps.silver.devops.gov.bc.ca/private-cloud/create but needs to be redirected to https://dev-pltsvc.apps.silver.devops.gov.bc.ca/</s> **- FIXED**
- [x]  ~61. The wording in the Edit Quota Request lacks connecting words and says: "All quota increase requests require Platform Services Team’s approval must have supporting information as per the Quota Increase Request Process."
Let's change it to "All requests to increase quotas must have supporting information and approved by the Platform Services Team in accordance with the Quota Increase Request Process."~**- FIXED**
- [x] <s>63. Just a UX suggestion: In Current Registry we see representative icons if the product is in Pending, Processing or provisioned state. In the New UI we only have grey writings. Current option gives more visual control over the products. Maybe we could think how to add this representation to the New UI. Maybe make writings different colours or add icons. </s> **- FIXED**
- [ ] 68. If the User tries to make a Create request not including themselves, they don't get visual error.
- [x] 69. ~If the User adds/deletes users in AWS Roles Dashboard the changes are not shown instantly without refresh. Ticket #1799.~
- [x] 70. ~When the User is on the Roles Tab in Public Cloud product and on any of sub-tabs except "Admins", the "ROLES" tab is not highlighted.~
- [ ]  71. If the Product is in the Pending or Processing state the Delete button is not disabled  Ticket #1847
- [ ] 73. The Deletion pop-up has mentions of the word Project which can be changed to Product.
- [ ] 74. When Create request is made and the Admin opens Product Page to review it, the page has the section called User Comment. Which doesn't have anything because user is not prompted on Submit. We need to either ask user for a comment or delete the section while admin opened to review it.
- [ ] 75. The Toggle to Show Deleted Projects can't be untoggled and/or doesn't refresh automatically.
- [ ] 76. History inside the Private Cloud product has filters and empty list button from the Products page and doesn't have history. Will we hide it on Prod?
- [ ] 77. Filtering by ministries doesn't provide option "All" after choosing one of them. (No live search by Ministry, though it is available for Cluster).
- [ ] 78. Refresh of the page after filtering does not refresh the filtering.

After User Testing with Abibat:
- [ ] 80. At the bottom of Login Page make "Note for Public Cloud:" a "Note for Public Cloud Hosting:"
- [ ] 81. In the description of Products Tab change "products" to "product sets" or "project sets".

- [ ] 83. Add ability to copy and paste license plate.
- [ ] 84. Add decommission information and link to Delete documentation to the Delete Popup.
- [ ] 85. Word Provisioning is confusing compared to Processing.
- [ ] 86. "Project set" in empty list instead of "Product set" or discuss.

After User Testing with Olena:
- [ ] 108. History Tab on Prod shows only Deletion (no Create and Edit). 
- [ ] 109. Admin can't see Rejected requests. Even with toggle "Show deleted products" is on.
- [ ] 110. Make Delete button instead of Options -> Delete.
- [ ] 118. Downloading .csv now includes deleted projects even if the user didn't toggle their visibility on.
- [ ] 121. On Delete Request initiated by TL, they receive the email with the name of PO instead of theirs.
- [ ] 122. After Rejection, the Create Request disappears completely for the User and for Admins

New:
- [x] ~123. The Products are not ordered in Products and In Progress tabs. Order them by last edit on top. Ticket #2115~ - **FIXED**
- [ ] 125. Jason Leach wants to see all the projects including deleted ones with the status "Deleted"

**Comment by Kolezhanchik** [comment]
@funtigr 30 and 33 Artem double check it, please
