### ISSUE TITLE
The API shoud have the concept of a profile

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#15]
The API should have the concept of a profile to serve as the anchor point for a project. This should be able to track basic information about a project.

- [x] Create profile endpoints in OpenAPI doc;
- [x] Create data model (using basic SQL);
- [x] Create API endpionts.
  - [x] Create
  - [x] Read #14
  - [x]  Update
  - [x] Delete
