### ISSUE TITLE
Add project deletion feature to  Project Registry 

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#157]
**Describe the issue**
As as a PO I want to be able to delete the projects that I have requested to provision. The Registry super admin users should be able to delete any project in the Registry.  

**Additional context**
The project edit page will have a button to delete the project. Clicking the button will show a pop up asking for a confirmation of the action, e.g. "Are you sure you want to delete this project? Note that deleting it will remove all 4 project namespaces in Openshift including the code that is currently running in them. This action cannot be rolled back." Upon the confirmation, the project record will be archived in the Registry DB with a timestamp for when its status changed. The project record will be removed from the project dashboard.  This will also trigger the GitOps part that will update the ARGO manifests for the project, and propagate the change to Openshift to remove the namespaces associated with this project.

The Provisioner does the actual deletion of resources.  The provisioner runs via Argo Workflows.  It uses an image built from the 'devops-fulfillment-pipeline' repo.

OpenShift resources deleted include:
* Artifactory ServiceAccounts
* Argo CD Applications and Project
* Namespaces

**ACS**
* Role
* Access Scope

**Manifests managed by Argo CD**
* Argo CD tenant app
* Project namespace files
* Vault Terraform files

**Keycloak
* Groups used for Argo CD access control

**Definition of done**
- [x] Update the Registry UI to support project deletion as per the specs above.
- [x]  Implement the integration bettween the web app and the GitOps backend to propage the deletion request to Openshift and remove the namespaces and other relevant data. (can be tracked in a separate ticket)
- [x] Document all pieces that need to be cleaned up in Openshift as part of the ticket tracking the GitOps part changes,

**Comment by IanKWatts** [comment]
A PR has been created in the devops-fulfillment-pipeline repo to enable this feature in the provisioner.

**Comment by IanKWatts** [comment]
Sep. 22 update - the PR for this is open and awaiting review from Justin Pye
https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/49
Justin is familiar with what was discussed for this, but PR could be approved by someone else if we want to keep this moving.

**Comment by IanKWatts** [comment]
PR has been updated
https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/49/files
