### ISSUE TITLE
 93. Review emails templates and their headers on logical and wording errors.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1978]
Amritpal and Pillar will review emails templates and their headers on logical and wording errors.

- [x]  94. Email Templates. Change phrase "The new Product or Technical Lead provided" to "The new Product Owner or Technical Lead". Also add "(-s)" after "Lead" in the phrase "The Product Owner and the Technical Lead have been".
- [x]  95. Email Templates. In all the email regarding Editing and Deleting remove all mentions of "new project set".
- [x]  96. Email Templates. Change the header of Request Received email headers to this: "Provisioning request received for the product name in AWS (for Public Cloud) / OpenShift (for Private Cloud).
- [x]  ~97. Email Templates. Change the signage in the bottom to Platform Services Team for Private Cloud and to Cloud Pathfinder Team for Public Cloud templates. This request branched out into a new ticket that Zhanna will work on.~ Ticket #2036
- [x]  98. Email Templates. Change "Hi 's Team" to "Hi Product Team".
- [x]  99. Email Templates. Change any mentions of Rocket Chat channels to just one: #devops-operations.
- [x]  100. Email Templates. Deletion request received email, change wording. "Your product deletion request for has been received." Same for Deletion Approved but "has been received and completed".
- [x]  101. Email Templates. Add default quotas to Provisioned email.
- [x]  102. Email Templates. Admin comment is not shown in Rejected email.
- [x]  103. Email Templates. Edit Request: "Your request for a resource quota has been completed. You can login to OpenShift cluster console using the link above and you will see the new resource quota values."
- [x]  104. Email Templates. Provisioning request received: "Provisioning request received for the product name in AWS/ OpenShift."
- [x]  105. Public Cloud Edit Summary email needs some wording or format changes see ticket #1889 for more information by Artem.

**List of all email templates for Pilar to review:** 
Private Cloud:

- [x] 94. [PrivateCloudRequestProvisioned] [PrivateCloudRequestApproval] Add a "(s)" when mentioning Technical Lead(s). "The new Product or..." should be "The new Product Owner or..." in the last sentence of the second paragraph.
- [x] 95. [PrivateCloudRequestApproval] [PrivateCloudCreateRequest] Remove or change the wording of "new project set" depending on the flow of the sentence.
- [x] 96. [PrivateCloudCreateRequest] Change the header from "New Request!" to "Provisioning request received for {Product Name} in OpenShift"
- [x] ~97. For all emails, change the signature in the bottom to "Platform Services Team" for Private Cloud templates. This request branched out into a new ticket that Zhanna will work on.~ Ticket #2036
- [x] 98. For all emails, change "Hi {Product Name}'s Team" to just a generic "Hi Product Team".
- [ ] 99. [PrivateCloudRequestApproval] [PrivateCloudRequestProvisioned] Change any mentions of Rocket Chat channels to just one: #devops-operations. Note: I checked the templates and they all seem to have the correct one currently.
- [x] 100. [PrivateCloudDeleteRequest] [PrivateCloudDeleteCompletion] For DeleteRequest, the heading is really long, and needs to be reworded to be more concise and informative at a glance. For DeleteCompletion, the wording is awkward, should also be past tense. E.g, "...deletion has been completed".
- [ ] 101. [PrivateCloudRequestProvisioned] Add default quotas to Provisioned email. -Amritpal will take this on
- [x] 102. [PrivateCloudRequestRejection] Admin comment is not shown in Rejected email. This has since been fixed, comments now appear in emails.
- [x] 103. [PrivateCloudRequestApproval] Edit Request: "Your request for a resource quota has been completed. You can login to OpenShift cluster console using the link above and you will see the new resource quota values." -No changes needed here, as we use a generic approval email for when an edit request or create request is approved. Although this should be changed in the future.
- [x] 104. [PrivateCloudCreateRequest] Change the header for this email to be more in line with something like: "Provisioning request received for the {product name} in OpenShift."
- [x] 105. No equivalent changes need to be made for Private Cloud

Public Cloud:

- [x] 94. [PublicCloudRequestProvisioned] [PublicCloudRequestApproval] Add a "(s)" when mentioning Technical Lead(s). "The new Product or..." should be "The new Product Owner or..." in the last sentence of the second paragraph. Also the wording here may not be correct for Public Cloud, as there are "namespaces" in Private Cloud, unsure of the terminology for Public Cloud/AWS.
- [x] 95. [PublicCloudRequestApproval] [PublicCloudCreateRequest] Remove or change the wording of "new project set" depending on the flow of the sentence.
- [x] 96. [PublicCloudCreateRequest] Change the header from "New Request!" to "Provisioning request received for {Product Name} in AWS"
- [x] ~97. For all emails, change the signature in the bottom to Cloud Pathfinder Team for Public Cloud templates. This request branched out into a new ticket that Zhanna will work on.~ Ticket #2036
- [x] 98. For all emails, change "Hi {Product Name}'s Team" to just a generic "Hi Product Team".
- [x] 99. [PublicCloudRequestApproval] [PublicCloudRequestProvisioned] Change any mentions of Rocket Chat channels to just one: #devops-operations. Note: I checked the templates and they all seem to have the correct one currently.
- [x] 100. [PublicCloudDeleteRequest] [PublicCloudDeleteCompletion] For DeleteRequest, the heading is really long, and needs to be reworded to be more concise and informative at a glance. For DeleteCompletion, the wording is awkward, should also be past tense. E.g, "...deletion has been completed".
- [ ] 101. [PublicCloudRequestProvisioned] There are no quotas for Public Cloud, so no equivalent changes need to be made here
- [x] 102. [PublicCloudRequestRejection] Admin comment is not shown in Rejected email. This has since been fixed, comments now appear in emails.
- [x] 103. No equivalent changes need to be made here, as there is no edit approval process for Public Cloud. Instead, we have an edit summary email that is sent to the users, summarizing the changes they have made.
- [x] 104. [PublicCloudCreateRequest] Change the header for this email to be more in line with something like: "Provisioning request received for the {product name} on AWS"
- [x] 105. [PublicCloudEditRequest] Public Cloud Edit Summary email needs some wording or format changes, see the comments in ticket #1889 for more information by Artem. The naming of the button is not intuitive "View Changes" as the summary of the changes are already displayed in the email, perhaps rename or move the location of this button ?

**Comment by Pilargit12** [comment]
- [x]  94. [PrivateCloudRequestProvisioned] [PrivateCloudRequestApproval] Add a "(s)" when mentioning Technical Lead(s). "The new Product or..." should be "The new Product Owner or..." in the last sentence of the second paragraph.
 - [x] 94. [PublicCloudRequestProvisioned] [PublicCloudRequestApproval] Add a "(s)" when mentioning Technical Lead(s). "The new Product or..." should be "The new Product Owner or..." in the last sentence of the second paragraph. Also the wording here may not be correct for Public Cloud, as there are "namespaces" in Private Cloud, unsure of the terminology for Public Cloud/AWS.
 
- [ ] 94 @Amritpal-Nijjar  please review the above those for now, I will continue with the rest through making more commits to the same PR - thank you for your help!

**Comment by Pilargit12** [comment]
- [x] 98. For all emails, change "Hi {Product Name}'s Team" to just a generic "Hi Product Team".
- [x] 98. For all emails, change "Hi {Product Name}'s Team" to just a generic "Hi Product Team".

 - [x] 99. [PrivateCloudRequestApproval] [PrivateCloudRequestProvisioned] Change any mentions of Rocket Chat channels to just one: #devops-operations. Note: I checked the templates and they all seem to have the correct one currently.
 - [x]  99. [PublicCloudRequestApproval] [PublicCloudRequestProvisioned] Change any mentions of Rocket Chat channels to just one: #devops-operations. Note: I checked the templates and they all seem to have the correct one currently.
 
- [x] 100. [PrivateCloudDeleteRequest] [PrivateCloudDeleteCompletion] For DeleteRequest, the heading is really long, and needs to be reworded to be more concise and informative at a glance. For DeleteCompletion, the wording is awkward, should also be past tense. E.g, "...deletion has been completed".
- [x]  100. [PublicCloudDeleteRequest] [PublicCloudDeleteCompletion] For DeleteRequest, the heading is really long, and needs to be reworded to be more concise and informative at a glance. For DeleteCompletion, the wording is awkward, should also be past tense. E.g, "...deletion has been completed".

- [ ] For @Amritpal-Nijjar  101. [PrivateCloudRequestProvisioned] Add default quotas to Provisioned email. -Amritpal will take this on
- [x]  **Nothing to update** - 101. [PublicCloudRequestProvisioned] There are no quotas for Public Cloud, so no equivalent changes need to be made here

- [x] **Nothing to update** -  102. [PrivateCloudRequestRejection] Admin comment is not shown in Rejected email. This has since been fixed, comments now appear in emails.
- [x] **Nothing to update** -  102. [PublicCloudRequestRejection] Admin comment is not shown in Rejected email. This has since been fixed, comments now appear in emails.

- [x] 103. [PrivateCloudRequestApproval] Edit Request: "Your request for a resource quota has been completed. You can login to OpenShift cluster console using the link above and you will see the new resource quota values." -No changes needed here, as we use a generic approval email for when an edit request or create request is approved. Although this should be changed in the future.
- [x]  **Nothing to update** 103. No equivalent changes need to be made here, as there is no edit approval process for Public Cloud. Instead, we have an edit summary email that is sent to the users, summarizing the changes they have made.

- [x] 104. [PrivateCloudCreateRequest] Change the header for this email to be more in line with something like: "Provisioning request received for the {product name} in OpenShift."
- [x]  104. [PublicCloudCreateRequest] Change the header for this email to be more in line with something like: "Provisioning request received for the {product name} on AWS"

- [x] **Nothing to update** 105. No equivalent changes need to be made for Private Cloud
- [x]  105. [PublicCloudEditRequest] Public Cloud Edit Summary email needs some wording or format changes, see the comments in ticket https://github.com/bcgov/platform-services-registry/issues/1889 for more information by Artem. The naming of the button is not intuitive "View Changes" as the summary of the changes are already displayed in the email, perhaps rename or move the location of this button ?

Off to you @Amritpal-Nijjar for final review, please note that 97 will need to be passed on to @Kolezhanchik (she is expecting this already) 

Let me know if you have any questions!

**Comment by Kolezhanchik** [comment]
@Pilargit12 
95 - still can see "new project set" in create request email for public and private cloud
96 - can see "New Request!" for Admins' email, are we going to keep it for Admins?
