### ISSUE TITLE
New UI Registry Bugs and Enhancements

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2123]
Priority: high (H), medium (M), low (L)
Effort/size: large (L), medium (M), small (S)
Type: bug (B), enhancement (E)

**1st batch of improvements: - Sprint of Mar 14 - Apr 3** 
- [x] 142. Complex Changes: Ryan L.: Products Page: Add the names of the columns and ability to sort by columns. Ticket #2288
- [x] 39. UI: Prabhu: Request Page: I found entering incorrect account codes it would not tell me specifically what was wrong, only that it was wrong. The app team has decided to add an Info icon for each coding line to explain the requirements for the financial data input and limit the input value to only numbers - Ticket #2215

**2nd batch of improvements: - Sprint of Apr 4 - Apr 24** 
- [x] 83. UI: Products Page/ Product Page: Add ability to copy and paste license plate. Ticket #2313
- [x] 110. Make Delete button instead of Options -> Delete. Ticket #2314
- [x] 77. UI: Products Page: Filtering by ministries doesn't provide option "All" after choosing one of them. (No live search by Ministry, though it is available for Cluster). Ticket #2392.
- [x] History Tab - Mock Up Implementation #2436. 

**3rd batch of improvements: - Sprint of Apr 25 - May 15**
- [x] 127. Add a section to the email template about a change request "this request/change was made by [insert a name of the person who made a request]". We can even add this section to the email about creating a product stating who created this product. Ticket #2576
- [x] 143. UI: Abibat: Products Page: The arrow button confuses and is grayed out. - The team decided to remove the arrow icon as it doesn't have useful functionality. Ticket #2712
- [x] Update CSV downloaded file format: Ticket #2713
- 145). CSV: Luke: Acronyms in .csv downloaded file instead of full ministry names. The request is to replace the acronym with the full Ministry name.
- 146). CSV: Luke: Make column names readable.
- [x] 144. UI: Jason L. Products Page: Go Back Arrow button (on the left top) from Request leads to Products Tab. Ticket # 2714. 

**4th batch of improvements: - Sprint of May 16 - Jun 5**
- [x] Create Home Page (134. UI: Ryan L.: Login Page: Avatar makes User think they are logged in.) - Move the Login button to the top right corner instead of an avatar. Add Home Tab and make the info of the Login page part of the Home page - Ticket #2309 

**5th batch of improvements: - Sprint of Jun 6 - 26**

- [x] Home/Login Page Enhancements: Ticket #2960
- 132). UI: Abibat: Login Page: Blue disclaimer: Note for Public Cloud Hosting (add this word).
- 133). UI: Jason L.: Login Page: Move Blue disclaimer to the top.
- 135). UI: Ryan L.: Login Page: "If you are a PO" - maybe ad "or TL".
- 136). UI: Ryan L.: Login Page: Place "Before you start" section before "Register a new product" section.
- 138). UI: Ryan L.: Login Page: Place Blue disclaimer in "Before you start" section.
- 139). UI: Luke: Login Page: "OpenShift 4" - is mentioning version important?

**6th batch of improvements: - Sprint of Aug 8 - Aug 28**
- [x] Update UI Delete confirmation modal update: Ticket #3157
- 154). UI: Jason L.: Delete Request: In Deletion Popup make "this can't be undone" bolder and/or bigger. Team suggestion - Combine the message that we have in yellow with "This can't be undone". Put it at the top of the popup, make it red. 
- 155). UI: Luke: Delete Request: Make a red (or red on hover) "Delete" button at the bottom. 
- 152). UI: Abibat: Delete Request: Add data about decommission of the product and link to documentation to Deletion Popup. Clarify if the message/link will be different for different providers. https://digital.gov.bc.ca/cloud/services/public/intro/#closure

**7th batch of improvements: - Sprint of Aug 29 - Sep 18**
- [x] 54. Emails: Exceeding comments and dividers in emails - Zhanna will check the email templates to see if it's still an issue. Ticket #3731

**8th batch of improvements: - Sprint of Sep 19 - Oct 9**
- [x] 165. UI: Ryan L.: Products Page: Cluster in separate column. - Add sort by cluster and by ministry functionality. Ticket #3730
=======================================================================================
**Unfixed items - Low Priority/Part of Other Tasks that will be done later:** 
- [x]  11. UI: Products Page: When the Product is Provisioned it's status is not updated on the page automatically. User has to refresh the page - Wait. New feature, not a bug. Size: L. Priority: M - the team has decided not to proceed with this since it's a low priority and huge effort
- [x]  52. UI: Request Page: Account Coding and Project Budget are editable (though not saveable) in Pending Request view. Priority: L
- [x]  68. UI: Create/Edit Pages: If the User tries to make a Create request not including themselves, they don't get visual error. Priority: L - this is not a bug but expected behaviour 
- [x]  55. Emails: The emails do not show the comments from admin
- [x]  74. UI: Request Page: When Create request is made and the Admin opens Product Page to review it, the page has the section called User Comment. Which doesn't have anything because user is not prompted on Submit. We need to either ask user for a comment or delete the section while admin opened to review it. - after the team discussion, we decided to have a section with user comments in the request page.
- [x]  75. UI: Products Page: The Toggle to Show Deleted Projects can't be untoggled and/or doesn't refresh automatically.
- [x]  109. Admin can't see Rejected requests. Even with toggle "Show deleted products" is on. - to clarify with Olena what kind of rejected requests she'd like to see in the history (e.g. rejected request for a newly created product that was never approved/created or a request for an existing product) 
- [x] 148. UI: Luke: Edit Request: Maybe collapse Common Components on Edit. - this will be a part of the new design and all other sections will be collapsable 
- [x] 151. UI: Ryan L.: Edit Request: Change popup to say if approval needed or not, to understand if it needs time or will be done instantly. - this is part of the ticket #3637 and will get fixed when the ticket is completed
- [x] 156. UI: Jason L.: Approval: Make Product non-editable while approving Delete Request. - Team confirmed that this is still a bug for admin users. 
- [x] 161. Complex Changes: Ryan L.: Edit Request/Product Page: Show the usage of Quota for Users to understand if they need that much or need more. 
- [x] 162. Complex Changes: Ryan L.: Edit Request: Create Ability to change Description and Contacts while the Quota is In Review (often use case). - huge effort, low priority. The team has decided not to proceed with this now
- [x] 164. UI: Ryan L.: Products Page: Add sorting by name of TLs and PO. - clarify with Ryan if it't still needed given that there is a search functionality by user name
=======================================================================================
**FIXED or NOT RELEVANT anymore items:** 
- [x] 3. Logo is leading to the Private Cloud products page even on the Public Cloud tab. - It would be nice to do before go-live. Priority: M. Size: S. Assignee: Oamar. Ticket #1509 - **FIXED**
- [x]  12. Add human friendly names for the ministries - Wait but it would nice to do before. Priority: M. Size: M - **FIXED**
- [x]  13. The bearer token in the test is “abcd”. Should we change it to be received from the authentication website? Actually it works without token too - Wait. Priority: L/M. Size: S/M - this should be a separate item not part of this epic. We have 2 tickets for that: #2213 for private cloud and #876 for public cloud
- [x]  14. Now after login we are redirected to Private Cloud products. What will be the case when a user only uses Registry for Public Cloud only? - Wait. Priority: L. Size: TBD - wait until we have a Home page and this will be resolved
- [x]  15. If one of AG, EMBC, HOUS or PSSG ministries is chosen, the disclaimer with checkbox is not showing up. - Wait. Priority: H. Size: M. *Note: "Disclaimer" is misspelled in the footer.
- [x]  16. Input in Search fields makes the live search but if user hits Enter in the end the Search condition is erased. - Wait. Priority: L, Size: S
- [x]  19. The Requests are not sorted by name, nor creation date, nor last edit date, nor request type - will be fixed in Oamar's PR. Artem to check and test once completed. - **FIXED**
- [x]  23. Now we have the namespaces shown but they are not links that lead to OpenShift - will be fixed in Oamar's PR. Artem to check and test once completed.
- [x] 44. Restricting special characters for some fields is a necessary requirement. Edition - this is only about the Product Name. We need to clarify with Olena if this is also required for the private cloud. Also, we need to clarify what special characters can be allowed (e.g. "-" ). Ticket #2216

Feedback after session with Iryna:
- [x]  50. Create request doesn’t send emails
- [x]  51. Return Decimal to Account Coding
- [x]  53. Change or remove name in the Email as TL gets the name of PO there. Priority: M. - We changed the template to address clients with "Hi, Product Team" vs addressing a person individually, by the role. This fixed that bug. - **FIXED**

After User Testing with Abibat:
- [x]  81. In the description of Products Tab change "products" to "product sets" or "project sets".
- [x]  86. "Project set" in empty list instead of "Product set" or discuss.

New:
- [x] 123. The Products are not ordered in Products and In Progress tabs. Order them by last edit on top. Ticket #2115 - **FIXED**
- [x] 57. Complex Change: The old users have the names that were taken from IDIR a long time ago - Fixed.
- [x]  71. UI: Request Page: If the Product is in the Pending or Processing state the Delete button is not disabled Ticket #1847. This will be fixed with through the ticket #2391. 
- [x]  73. UI: Delete Request: The Deletion pop-up has mentions of the word Project which can be changed to Product. - fixed.
- [x]  76. UI: Product Page: History inside the Private Cloud product has filters and empty list button from the Products page and doesn't have history. Will we hide it on Prod? - it's hidden on prod for now and when we'll be working with the history page, we'll have it as a separate epic. 
- [x] 78. UI: Products Page: Refresh of the page after filtering does not refresh the filtering. - not needed anymore. 
After User Testing with Olena:
- [x]  118. Downloading .csv now includes deleted projects even if the user didn't toggle their visibility on.
- [x]  121. On Delete Request initiated by TL, they receive the email with the name of PO instead of theirs.
- [x] 125. Jason Leach wants to see all the projects including deleted ones with the status "Deleted"
- [x] 126. Create a Home page for the Registry
- [x] 129. Inactive deleted products are shown on the 'In Progress' tab
- [x] 147. UI: Jason L.: Edit Request: Gray out the columns user is not editing now. Fix Template and Route of the Request Page - Private & Public Cloud.- this is not needed to be fixed. The unused Request template can be used/repurposed for the History tab when/if we will provide a link to the previous requests
- [x] 128. After changing Ministry only, Contacts only, Common Components Only or Name/Description Only (which is approved automatically) Admin receives an email about the Request that needs a review. - check later if it's fixed with email revisioning tickets
- [x] 130. The Delete Approved email in the Private Cloud has text about provisioning namespace and that PO and TL now have access to the namespaces, which is not true (the Universal template of Provisioned). - check later if it's fixed with email revisioning tickets
- [x] 140. UI: Abibat: Create Page: Modal in Public Cloud has words about Onboarding. Is that necessary as person should have gone through it by the time they reach it.
- [x] 141. UI: Olena: Products Page: Change Description: "These products have pending requests associated with them and admins are approving them"
- [x] 142. UI: Olena: Products Page: In Progress tab: The description mentions Products instead of Requests.
- [x] 131). UI: Abibat: Login Page: Login button is closer than Register button and they have the same function. New Users could miss info between them - not relevant anymore
- [x] 137). UI: Ryan L.: Login Page: Users may be confused by BC IDIR thing. Not everyone knows what it is - not relevant anymore
- [x] 149. Emails: Olena: Add to subject "Provisioning request received" this: "for the <product name> in {AWS | OpenShift}
- [x] 150. Emails: Olena: Review and rephrase email subjects.
- [x] 153. UI: Abibat: Product Page: "Provisioning" is confusing compared to "Processing".
- [x]  157. UI: Jason L.: Products Page: Show Deleted Products but mark them Deleted (done, check if marked before approval).
- [x]  158. UI: Abibat: A lot of different terminology for same things.
- [x]  159. UI: Jason L.: Products Page: Make "Product name" bold, not the "Cluster". 
- [x]  160. Complex Changes: Ryan L.: More than 2 TLs or ministry sector super edit admin.
- [x]  163. UI: Ryan L.: Product/Request Pages: Add full name of the Product near the license plate.
- [x]  166. Luke: Youtube videos with walkthrough of different flows. 
- [x]  167. UI: Products Page: In Progress tab Search doesn't show empty list if no entries found by prompt.
