### ISSUE TITLE
Create Admin and Reader Roles for Private and Public Clouds

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2284]
**Describe the issue**
We need to create the additional roles to the registry that we enable the users to viewer or edit/approve products. 

**Admin** - can view, edit and approve all the products in the Registry:

- Global (both private and public)
- Private Cloud only
- Public Cloud only

**Editor** - can view and edit all the products in the Registry:
- Ministry only (both clouds)

**Reader** - can view/read all the products in the Registry:
- Global (both private and public)
- Private Cloud only
- Public Cloud only
- Ministry only (both clouds)

**Additional Context**

- We need to re-assign those roles to the users that used to have it before.
- Zhanna found a list of all previous users that had read-only admin roles. 

**Definition of done/Acceptance Criteria**

- The above mentioned additional roles have been created:
**Admin** - can view, edit and approve all the products in the Registry:

- [x] - Global (both private and public)
- [x] - Private Cloud only
- [x] - Public Cloud only
- [x] - Ministry only (both clouds)

**Reader** - can view/read all the products in the Registry:

- [x] - Global (both private and public)
- [x] - Private Cloud only
- [x] - Public Cloud only
- [x] - Ministry only (both clouds)

**Editor** - can view and edit all the products in the Registry:

- [x] - Ministry specific (both clouds)

- The roles are assigned to the users.
