### ISSUE TITLE
Emails refactoring/improving according to docs

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#2393]
**Private Cloud**

- [x] Scenario 1 - Ticket #2431:

- 1). Scenario 1, Provisioning request email sent to admins is missing a period for the second sentence. 
- 2). Scenario 1, UI has a comment field for approving a create request, these comments do not show in the provisioned email. Comments for the email are not in the documentation either. In conclusion we get rid of the comments box for approving a create request
- 3). Scenario 1, Update the emails documentation for a create request rejection, we will add the product name to the subject, and not have product details in the email body. This is to be consistent with the previous emails of the registry.
- 4). Scenario 1, For the provisioned email that gets sent to the users add this link: https://developer.gov.bc.ca/docs/default/component/chefs-techdocs/About/SoAR-and-Compliance/#advanced-cluster-security-acs

- [x] Scenario 2 - Ticket #2432:

- 5). Scenario 2, "Edit request received" is the subject line for both emails received by user and admin, change the subject for the email admins
- 6). Scenario 2, The second sentence for an edit request email needs a period
- 7). Scenario 2, Comments do not appear for the admins for an edit request
- 8). Scenario 2, Admins do not currently see the current and requests quotas for the edit request
- 9). Scenario 2, Edit request approval is sending a product provisioned email, this is the wrong email.  We might have to create a new template for the scenario of approving a edit request with resource quota increase.
- 10). Scenario 2, Edit request approved with resource increase documentation seems to be wrong, and needs to be updated. Update the documentation to get rid of: Security Tools Info, Artifactory Info, Vault Info, ACS Info, Sysdig Info.
- 11). Scenario 2, Rejecting a resource quota increase documentation should have the current and requested quotas. The email needs to be updated to reflect this documentation change.

- [x] 12) Add documentation that handles the scenario of a mixed request (quota increase, plus something else changed like contacts). Ticket #2433 (Artem)

- [x] Scenario 3. Ticket #2434 (Zhanna)

- 13). Scenario 3, needs to be updated, as resource changes (upgrades and downgrades) go through an approval process
- 14). Talk to Luke about auto approve for quota downgrades -related to point 13)
- 15). Scenario 3. Edit Request: No Resource Quota Increase: is sending emails to admins, this should not be the case. The wording for the email needs to be revisited.
- 16). Scenario 3, update documentation, should send "request received email" to users (mention a follow up email will be sent once changes have been provisioned), and then after provisioning, a summary of the changes email is sent.

- [x] Scenario 4 - Ticket #2435 (Amritpal)

- 17). Scenario 4, admin did not receive email.
- 18). Scenario 4, Namespace details is in the email but not in the documentation. Update the documentation
- 19). Scenario 4, the email is good, update the documentation to not have product details
- 20). Scenario 4, approving a delete request has comments box, get rid of this comments box entirely.
- 21). Scenario 4, Approving a delete request sends a new product provisioned email, instead have Product Details (Name, Description, Ministry, Contacts of PO/TL(s)) and Namespace details, so we must update the documentation.

**Public Cloud**
1) Update Public Cloud email documentation for the email scenario of expense authority
2) Scenario 1, admin receives email for a create request that says Namespace details, instead of Landing Zone Details, also is missing Budget, and account coding, also the footer needs to be removed
3) Scenario 1, user receives email that has a weird footer info, needs to be updated.
4) Scenario 1, related to point 1, add documentation that mentions that the expense authority gets an email upon product approval
5) Check all emails for a double mention of Cloud Pathfinder team in the footers
6) Get rid of the comments box for when approving a create request
7) Scenario 2, edit request is sending a provisioned email, this should not be the case. Only send the edit summary email
8) Ask public cloud if there is a callback for an edit. Explore possibility of sending an email before the edit is provisioned and sends the edit summary email. Update docs if we do implement this change
9) Scenario 3, change subject of rejection email to say something like "Request has been rejected for [product name]"
10) Scenario 3, for reject delete email, add product details section
