### ISSUE TITLE
Sprint Priorities for Apr 4 - Apr 24

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2428]
**Sprint priorities:**

1. Emails refactoring/improving according to docs (Team). => _Improving internal processes_

- [x] 1.1. Scenario 1. Ticket #2431
- [x] 1.2. Scenario 2. Ticket #2432
- [x] 1.3. Scenario 3. Ticket #2434
- [x] 1.4. Scenario 2. Ticket #2435
- [x] 1.5. Add documentation that handles the scenario of a mixed request. Ticket #2433

2. E2E test
- [x] 2.1. E2E test - Add conditional logic for "Login with KeyCloak" button on visual login (Artem). Ticket #2397 => _Improving internal processes_
- [x] 2.2. E2E - Create Delete Test#2401 (Artem). Ticket #2397 => _Improving internal processes_
.
- [x] 3. Frontend Implementation for the comments field for admins. Ticket #2312 (Amritpal) => _New feature for the internal users_

4. Improving the Registry by fixing bugs/implementing enhancements (Team) => New features/Fixing bugs

- [x] 4.1. UI: Products Page/ Product Page: Add ability to copy and paste license plate. Ticket #2313 => _New feature for the community and internal users_
- [x]  4.2. Make Delete button instead of Options -> Delete. Ticket #2314 => _New feature for the community and internal users_
- [x] 4.3. UI: Products Page: Filtering by ministries doesn't provide option "All" after choosing one of them. (No live search by Ministry, though it is available for Cluster). Ticket #2392. => _New feature for the community and internal users_
- [x] 4.4. URGENT. In Public Cloud if User deletes the product, public-admin can't approve the Deletion as it is in inactive state. (Zhanna) Ticket #2429
.
- [x] 5. Implement History tab UI. (Zhanna) Ticket #2436

**ADDITIONALLY added during the Sprint:** 
- [ ] Implement History tab UI for the Public Cloud. (Zhanna) Ticket #2538
- [x] Bug - Private-admins are not able review requests. Ticket #2438
- [x] Bug - Private-Admin can't see the lab clusters. Ticket #2465
- [x] Bug - Let Responsibility Centre (RC) (Account Coding) filed contain letters. Ticket #2501
- [x] Make quota downgrade Provision automatic. Ticket #2496
- [x] Create Analyzer, public-analyzer and private-analyzer roles. Ticket #2516
- [ ] Comment bubble UI implementation. Ticket #2530

======================================================================================
**Stretch goals:**

6. Refactoring the codebase to minimize technical debt for future implementations  => _Improving internal processes_:
- [x] 6.1. Client & Server base components. (Junmin) Ticket #1954   
- [x] 6.2. Re-organize cloud routes. (Junmin) Ticket #2514
- [ ] 6.3. Convert list pages to client components. (Junmin) Ticket #2528
.
- [ ] 7. Splitting Gold and Gold DR provisioning

======================================================================================
**Categories:**

=> _New feature for the community and internal users_
=> _New feature for the internal users only_
=> _Fixing bugs_
=> _Improving internal processes_
=> _Training/team learning sessions_
