### ISSUE TITLE
Sprint Priorities for Apr 25 - May 15

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2554]
**Sprint priorities:**

- [x] 1. continue with admin comments page - edit and delete comment functionality
- [x] 2. continue with email scenarios - public cloud
- [ ] 3. history tab/individual request/requested project page
4. Improving the Registry by fixing bugs/implementing enhancements:
- [x] 4.1. Add a section to the email template about a change request "this request/change was made by [insert a name of the person who made a request]".
- [x] 4.2. The arrow button confuses and is grayed out. - The team decided to remove the arrow icon as it doesn't have useful functionality. Ticket #2712
- [x] 4.3. Update CSV downloaded file format: Ticket #2713
- [x] 4.4. Grey out non-changed quota fields and only show changed ones
.
- [x] 5. Refactoring the codebase to minimize technical debt for future implementations
- [x] 6. E2E testing - Integrate to CI Pipeline

==========================================================================
**Stretch goals:**

- [ ] 6. Azure Project Provisioning Capability
- [x] 7. Splitting Gold and Gold DR provisioning
- [ ] 8. .csv download API
- [ ] 9. provisioner cron job from old API Registry 
- [ ] 10. Alex's new product page UI 

**Categories:**

=> _New feature for the community and internal users_
=> _New feature for the internal users only_
=> _Fixing bugs_
=> _Improving internal processes_
=> _Training/team learning sessions_
