### ISSUE TITLE
Sprint Priorities for Sprint May 16 - June 5

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2812]
**Sprint priorities:**

- [x] 1. Separate admin comments for Products and Requests
- [x] 2. Fix bugs found in round 2 of email scenario review
- [x] 3. Azure Project Provisioning #2577
- [ ] 4. provisioner cron job from old API Registry
- [x] 5. Test label for products created for testing and automatic deletion (e.g. 30 days)
- [ ] 6. history tab/individual request/requested project page - on hold until the team gets an update from Alex regarding the design
- [x] 7. E2E Testing
==========================================================================
**Stretch goals:**
- [ ] 8. Alex's new product page UI
- [x] 9. .csv download API 
- [ ] 10. API integration tests and E2E tests

**Categories:**

=> _New feature for the community and internal users_
=> _New feature for the internal users only_
=> _Fixing bugs_
=> _Improving internal processes_
=> _Training/team learning sessions_
