### ISSUE TITLE
Sprint Priorities for Sprint June 6 - June 26

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#3031]
Sprint priorities:

- [ ] 1. Mailchimp Integration and Deprecate Mautic (Zhanna) - Ticket #3040
    - Discuss whether to deprecate the current mail subscription page and migrate it to the registry app.
    - Explore Mailchimp to assess the possibility of maintaining topics as `configuration of code`.
    - Investigate Mailchimp's API endpoints and their usage.
- [x] 2. App Events System (team). Ticket #3041, #3042
    - Discuss which event types we want to track in the database.
    - Update the database schema and codebase accordingly.
- [ ] 3. E2E Gherkin Scripts (Artem). Ticket #2959
    - Continue working on the `feature` files to complete the list.
- [x] 4. API Test Scripts (Junmin)
    - Explore the fundamental structure of testing conventions and mocking resources/sessions.
    - Write tests for the browser API in the private cloud environment.
    - Write tests for the browser API in the public cloud environment.
    - Write tests for service API endpoints.
- [x] 5. Finish backend logic for cron job  (Artem)
    - marking products as provisioned
    - send notifications to RC in case status is `failed` 
 - [x] 6. User testing of admin comments  (Amritpal)
    - create script/questions/notes template
    - live user testing session with key users
- [x] 7. Home/Login Page Enhancements: Ticket #2960 (Amritpal)
- [x] 8. Revisit public cloud emails scenarios from Azure prospective
==========================================================================
Stretch goals:

- [ ] 9. automatic scheduled `Temporary` products deletion 
- [ ] 10. history tab/individual request/requested project page - on hold until the team gets an update from Alex regarding the design - [ ] 8. history tab/individual request/requested project page - on hold until the team gets an update from Alex regarding the design
