### ISSUE TITLE
Sprint Priorities for Sprint June 27 - July 17

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#3231]
Sprint priorities:

- [ ] 1. Mailchimp Integration and Deprecate Mautic (Zhanna) - Ticket #3040
    - Add subscription page to registry page. - private cloud segment A
    - Investigate Mailchimp's API endpoints and their usage.
    - Add product contacts to MailChimp's proper segment via API. private cloud segment B
    - Remove product contacts from MailChimp's proper segment via API. private cloud segment B
```
    - Scenario: 1
    - User A want to receive notification no matter what the user belongs to a product or not.
    - User A used to work for Product A, and removed from the Product A at some point.
```
    - Before implementation, please discuss with team about the feasibility of the adapting cronjob/scheduler.

- [ ] 2. automatic scheduled `Temporary` products deletion  (Zhanna) 
    - send delete request for temp product sets in 30 days after `createdAt`
    - Grant Admin and Private-Admin permission to uncheck Temporary Label for Temporary Products#3242

- [x] 3. E2E Gherkin Scripts (Artem). Ticket #2959
    - Continue working on the `feature` files to complete the list.

- [ ] 4. Add 'other contacts' contacts to Private public product #3097 (Junmin)
    - list of emails (Gov. emails) -> product notifications / mailChimp

- [ ] 5. Add `email sandbox` (unknown) #3225
    - Mock CHES Service
    - Deploy MailPit

- [ ] 6. API integration testing; cont' (Amritpal)
   - Admin comments routes
   - NATs messages
   - Email messages; consider using https://www.npmjs.com/package/cheerio
==========================================================================
Stretch goals:

- [ ] 7. send notification PO/TL to notify about coming deletion event of temp products (schedular)#3253
- [ ] 8. history tab/individual request/requested project page - on hold until the team gets an update from Alex regarding the design
