### ISSUE TITLE
Add PVC Count Quota Controls to Registry

### ISSUE THREAD

**Issue by j-pye** [bcgov/platform-services-registry#345]
**Describe the issue**
A decision has been made to increase the allowed number of PVCs per namespace based on Quota T-Shirt size. 

| Quota Size | PVC Count |
| ----------- | ----------- |
| Small | 20 |
| Medium | 40 |
| Large | 60 |

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Fronted Updated to show PVC Count per Quota Size
- [x] API Updated to Pull the PVC Count from the DB and Pass it through NATS
- [x] DB Updated with PVC Count field
- [x] Provisioner Updated to support new PVC Count field
- [x] Generation Tested
- [x] Existing Projects Synced with new PVC Count values

**Comment by j-pye** [comment]
A workaround has been put in place to support this until the Registry Application can be updated to be the source of truth for this information.
