### ISSUE TITLE
Sprint Priorities for Sprint Sep 19 - Oct 9

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3797]
**Team Sprint Capacity - 68%**

**Sprint Priorities:**
- [ ] **1.** OCP API endpoint integration
    - Backend logic with API endpoint #3635
    - UI/email enhancement based on the auto-approval logic #3637
- [ ] **2.** Public cloud costs
    - Research on integration Public Cloud Project Cost Display for AWS and Azure #3800
- [ ] **3** Finalizing eMOU workflows
   - Conduct User Feedback Session on eMOU Workflows Before Production #3798
   - Final Touch-Up of eMOU Workflow and Production Deployment #3799
- [ ] **4.** Add Cloud provider selection reason (Text field) for Public Cloud. Ticket #3636
- [ ] **5.** E2E automated scripts cont` - Tickets #3812 & #3814
- [ ] **6.** Common components
   - Generic Input component #2827
   - Generic Textarea component #2828
- [ ] **7.** Search, Filter, and Sort Functionality improvements
   - Enhance Search, Filter, and Sort Functionality on Private Cloud Product Page #3165
   - Enhance Search, Filter, and Sort Functionality on Private Cloud Request Page #3166
   - Enhance Search, Filter, and Sort Functionality on Public Cloud Product Page #3167
   - Enhance Search, Filter, and Sort Functionality on Public Cloud Request Page #3168
---

**Stretch Goals:**

- [ ] [Email Sandbox] Mock CHES Service - #3225
- [ ] - [ ] **8.** Others
   - API Registry & MailChimp - Removed Label Bug. Ticket #3606
   - Restriction on the distinct PO and TL #3314
   - Deprecate and Remove `Mautic` Integration #3793
