### ISSUE TITLE
Sprint Priorities for Sprint Oct 10 - Oct 30

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#3959]
**Sprint Priorities:**
- [x] **1.** OCP API endpoint integration (qouta auto-approval)
- [x] - research for getting Storage usage metrics #3960 
- [x] - Automate resource quota change review logic - Increase Request (Storage) #3813
.

 - [x] **2.** "light" project set for the Private Cloud 

- [x]     - Research Spike: Evaluate the feasibility of "light" project set (less than 4 accounts) provisioning for Private Cloud #3965
- Documentation/insights/use cases 
.
- [x] **3** Add a new role of Billing Reader, which allows downloading signed eMOUs #3937
.
- [x] **4.** Rocketchat alerts and Notifications 

- [x]     - Send Rocketchat alerts when Airflow tasks fail #3954
- [x]     - Enhance Rocket.Chat Notifications for Deployment Status #3794
.
- [x] **5.** E2E automated scripts cont` - ongoing task 
- [x] - Tweak Create tests for Public and Private cloud after UI changes. Ticket #3989
- [x] - Tweak Edit Test to run in the GitHub actions. Ticket #3812
- [x] - Change E2E tests to correspond to new Modals. Ticket #4121
.
- [ ] **6.** [Email Sandbox] 

- [ ]    - [Email Sandbox] Deploy Mail service to view emails in dev environment #2700
- [ ]    - [Email Sandbox] Mock CHES Service #3225

---

**Stretch Goals:**
- [x] **8.** Change all registry titles to sentence case #3365
- [x] **9.**  deprecate admin emails by pulling emails from Keycloak by roles #3792
- [x] **10.**  Add Container Image Scanner to GitHub Actions Workflow #2692
- [ ] **11.** Restriction on the distinct PO and TL #3314

---

**Additionally Completed During the Spring:**

- [x] Organize DB service methods #3936
- [x] Implement Commit Message Linting with Conventional Commits #3118
- [x] Fix Airflow task to delete temporary products #4005
- [x] "light" project set for the Private Cloud - Zero qouta namespaces #3966
- [x] minor UI changes ( 1. for eMOU review email, display Hi OCIO Cloud Director, instead of displaying EA's name 2. display more information of submitters and decision maker's detail on popup of the progress bar on requests page) #4014
- [x] Bug fix - When User changes Quota in Private Cloud and switches browser tab, the changes get reset #4012
- [x] Change titles, button and tooltip texts to 'sentence case' #4010
- [x] Add side panel for assigned tasks (sign eMOU, review eMOU) #4018
- [x] Revisit modal components and its usage #3791
- [x] Remove all references to "quota edit requests" in the Registry #3942
- [x] NextJS 15 Upgrade #4076
- [x] Automate resource quota change review logic - Backend Logic and Endpoint #3635
- [x] Automate resource quota change review logic - UI Changes #3637
- [x] Modal component replacements #4055
- [ ] Bug: When Private-Reviewer changes quota in the Request, they need to enter Justification fields #4110
