### ISSUE TITLE
Sprint Priorities for Sprint Nov 21 - Dec 11

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#4297]
**Sprint Priorities:**
- [ ]  **1.** Testing of the Automated resource quota change #4176
- [x]  **2.** Resource numeric inputs #4188, #4310, #4312
- [ ]  **3.**  Enable requesters to cancel their active requests independently. #4276
- [x]  **4.** Private Cloud eMOU feature (gather requirements) #4116
- [ ]  **5.** Refresh access token from Keycloak (Research + implementation) #4026
- [ ]  **6.** Email Sandbox environment setup #3225
- [ ]  **7.**  Increase coverage by E2E automated tests - ongoing
