### ISSUE TITLE
Sprint Priorities for Double Sprints: Dec 12 - Jan 1 & Jan 2 - Jan 22

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#4490]
**Sprint Priorities:**
- [x]  **1.** Automated resource quota change #4488 
- [x]  **2.** Additional subscribers in NATS message #4481
- [x]  **3.**  Enable requesters to cancel their active requests independently. #4276
- [x]  **4.** Add "Get" /product API endpoint #4397
- [x]  **5.** Add webhook URL on the private cloud product's form #4398
- [x]  **6.** Event pages #3973
- [x]  **7** Task pages #3974
- [x]  **8**  Increase coverage by E2E automated tests - ongoing
