### ISSUE TITLE
Registry Go-Live Plan

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#831]
- data migration / freeze requests
- DNS record update
- 'down for maintenance' message
- community team to test new version (create/edit?)
- new version should be in prod days before the announced go-live date, aiming for Feb 8
- communication sent to community on Jan 23 outlining timeline and downtime/request freeze

**Comment by w8896699** [comment]
- [ ] manifest ffile for CI/CD pipline repo(ReadMe included in CI folder): https://github.com/bcgov-c/tenant-gitops-101ed4
- [ ] Database migration plan: https://github.com/bcgov/platform-services-registry-api/tree/main/src/migration
- [ ] Test Backup container( we are not using normal backup container as its not support mongo4.4, I put the code in registry api repo `mongo-44-backup-container` branch)
- [ ] provisioner migration plan: https://github.com/bcgov/platform-services-registry/blob/master/docs/new_registry_switch.md
- [ ] route cutoff/change
